# Generated by Django 3.0.2 on 2020-01-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='business',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='business',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='business',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='best_way_to_contact',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
