# Generated by Django 3.0.2 on 2020-01-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200120_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='best_way_to_contact',
        ),
    ]
