# Generated by Django 3.0.2 on 2020-01-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_job_best_way_to_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
