# Generated by Django 3.0.2 on 2020-02-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
